version: '3.4'

services:
  db_mssql:
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports:
      - "4307:1433"

  n5challenge.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DB_CNN_STRING=Server=db_mssql,1433;Database=N5Challenge;User=sa;Password=Pass@word;TrustServerCertificate=true;
      - KAFKA_BOOSTRAP_SERVER=broker:29092
      - ELASTICSEARCH_SERVER=elasticsearch:9200
      - ELASTICSEARCH_INDEX=default
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro